# ID стикеров для бота
stickers_id = [
    "CAACAgIAAxkBAAIDV2cfRLfpR83Jlk4ZLKjD5qfs3Px5AAJRUwACGivhSmV-VHVlnwvtNgQ",
    "CAACAgIAAxkBAAIDVWcfRLF6pnGQ0Q8mX1qYWH2VneEmAALNSgACBTbgSurrQZ6bl80zNgQ",
    "CAACAgIAAxkBAAIDUWcfRJ3JSpHd9okTkGqtK4f3jqZ6AAIdXwACiHTZSvcjS7IGRKtzNgQ",
    "CAACAgIAAxkBAAIDXWcfRMKawdnKG_ucxKq_hLmApGDSAAIQTgACyX_gSh-1WOOiZk3YNgQ",
    "CAACAgIAAxkBAAIDX2cfRMfltkyPsFSnb6ChYTHesbG5AAL2UgACwjrgSnk0mRVZy8MuNgQ",
]
